archive/homepage/urls.py
# coding: utf-8
from django.conf.urls import include, url
from django.views.generic import TemplateView

from archive.homepage.views import HomepageView

urlpatterns = (
    url(r'^$', HomepageView.as_view(), name='homepage'),
)

urlpatterns += (
    url(r'^', include('archive.users.urls')),
)

archive/reports/urls.py
# coding: utf-8

from django.contrib.auth.views import logout, login
from django.contrib import admin
from django.conf.urls import include, url
from .views import OutTasksPDF, InTasksPDF, StorageItemsPDF, RemovableItemsPDF, StorageItemsReport, RemovableItemsReport

urlpatterns = (
    url(r'^removable_items/$', RemovableItemsReport.as_view(), name='rem-items'),
    url(r'^storage_items/$', StorageItemsReport.as_view(), name='storage-items'),
    url(r'^removable_items_pdf/$', RemovableItemsPDF.as_view(), name='removable-items-pdf'),
    url(r'^storage_items_pdf/$', StorageItemsPDF.as_view(), name='storage-items-pdf'),
    url(r'^intasks_pdf/$', InTasksPDF.as_view(), name='intasks_pdf'),
    url(r'^outtasks_pdf/$', OutTasksPDF.as_view(), name='outtasks_pdf'),
)

archive/urls.py
# coding: utf-8

from django.contrib.auth.views import logout, login
from django.contrib import admin
from django.conf.urls import include, url
from .utils.decorators import anonymous_required
from archive.users.views import arc_login, arc_logout

urlpatterns = [
    url(r'^admin/', admin.site.urls),
]

urlpatterns += (
    url(r'^storage/', include('archive.storage.urls', namespace="storage")),
    url(
        r'^login/$',
        anonymous_required(login),
        {'template_name': "homepage/registration/login.html"},
        name="login",
    ),
    url(
        r'^arc_login/$',
        arc_login,
        name="arc_login",
    ),
    url(r'^logout/$', arc_logout, name="logout"),
    url(r'^api/', include('archive.api.urls', namespace="api")),
    url(r'^users/', include('archive.users.urls', namespace="users")),
    url(r'^reports/', include('archive.reports.urls', namespace='reports')),
    url(r'^', include('archive.homepage.urls')),
    url(r'^', include('archive.homepage.urls', namespace="registration_complete")),
)

archive/users/urls.py
# coding: utf-8
from django.conf.urls import include, url
from django.views.generic import TemplateView
from archive.users.views import ARCRegistrationView, exec_rule, license, UserCreate, UserChangePassword, UserEdit, UserDelete, UserList, UserDocs

urlpatterns = (
    url(r'^$', UserList.as_view(), name='users'),
    url(r'^docs/', UserDocs.as_view(), name='user_search'),
    url(r'^register/$', ARCRegistrationView.as_view(), name='register'),
    url(r'^create/$',
        UserCreate.as_view(), name='create'),

    url(r'^exec_rule/(?P<rule>\d+)/$',
        exec_rule, name='exec_rule'),
    url(r'^profile/(?P<pk>\d*)?',
        UserList.as_view(), name='user_profile'),
    url(r'^change_password/(?P<pk>\d+)/$',
        UserChangePassword.as_view(), name='change_password'),
    url(r'^edit/(?P<user>\d+)/(?P<pk>\d+)/$',
        UserEdit.as_view(), name='user_edit'),
    url(r'^delete/(?P<pk>\d+)/$',
        UserDelete.as_view(), name='user_delete'),
    url(r'^license/create/$',
        license, name='license_create'),
)

archive/homepage/views.py
# -*- coding: utf-8 -*-

from django.contrib.auth import logout, login
from django.views.generic import ListView, DetailView
from django.contrib.auth.models import Permission, User
from django.contrib.contenttypes.models import ContentType

from archive.storage.models import Item, ItemType
from archive.users.models import ArcUser

class HomepageView(ListView):
    model = ArcUser
    template_name = 'homepage/homepage.html'
    success_url = "/users/"

    def __init__(self, **kwargs):
        super(HomepageView, self).__init__(**kwargs)

    def get_queryset(self):
        result = super(HomepageView, self).get_queryset()
        user = self.request.user
        print ("LOG: HOMEPAGE: USER", user)

        '''
        if user.username == u'администратор':
            print("LOG: HOMEPAGE: item_type.edit", user.has_perm('storage.item_type.edit'))
            print("LOG: HOMEPAGE: item.edit", user.has_perm('storage.item.edit'))

            if not hasattr(user.user_permissions, 'add'):
                return result

            content_type = ContentType.objects.get_for_model(ItemType)
            permission = Permission.objects.get(
                                        codename='item_type.edit',
                                        content_type=content_type,
            )
            print("LOG: HOMEPAGE: permission", permission)
            user.user_permissions.add(permission)

            content_type = ContentType.objects.get_for_model(Item)
            permission = Permission.objects.get(
                                        codename='item.edit',
                                        content_type=content_type,
            )
            print("LOG: HOMEPAGE: permission", permission)
            user.user_permissions.add(permission)

            content_type = ContentType.objects.get_for_model(ArcUser)
            permission = Permission.objects.get(
                                        codename='user.edit',
                                        content_type=content_type,
            )
            print("LOG: HOMEPAGE: permission", permission)
            user.user_permissions.add(permission)

            print("LOG: HOMEPAGE: item_type.edit", user.has_perm('storage.item_type.edit'))
            print("LOG: HOMEPAGE: item_type.delete", user.has_perm('storage.item_type.delete'))
            print("LOG: HOMEPAGE: item.edit", user.has_perm('storage.item.edit'))
            print("LOG: HOMEPAGE: user.edit", user.has_perm('users.user.edit'))
        '''

        return result

archive/homepage/templates/homepage/base.html
{% load i18n static helper_tags %}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<style>
@font-face { font-family: DejaVu; src: url("/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf"); }
@page {size: a4 portrait; @frame header_frame {-pdf-frame-content: header_content; left: 50pt; width: 512pt; top: 50pt; height: 40pt;} @frame content_frame { left: 50pt; width: 512pt; top: 90pt; height: 632pt;} @frame footer_frame { -pdf-frame-content: footer_content; left: 50pt; width: 512pt; top: 772pt; height: 20pt;}}

</style>

<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <link rel="apple-touch-icon-precomposed" sizes="57x57" href="{% static "img/apple-touch-icon-144-precomposed.png" %}" />
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="{% static "img/apple-touch-icon-144-precomposed.png" %}" />
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="{% static "img/apple-touch-icon-144-precomposed.png" %}" />
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="{% static "img/apple-touch-icon-144-precomposed.png" %}" />
    <link rel="stylesheet" type="text/css"
          href="{% static "css/reset.css" %}"/>
    <link rel="stylesheet" type="text/css"
          href="{% static "css/layout.css" %}"/>
    <link rel="stylesheet" type="text/css"
          href="{% static "css/jquery-ui.css" %}"/>
    <link rel="stylesheet" type="text/css"
          href="{% static "css/jquery.dataTables.min.css" %}"/>
    <!--[if IE 6]>
        <script src="{% static "js/pngfix.js" %}"></script>
        <script>DD_belatedPNG.fix('.fixThis');</script>
    <![endif]-->
    <script type="text/javascript"
            href="{% static "js/jquery-1.12.4.js" %}"></script>
    <script type="text/javascript" src="{% static "js/jq-1.4.2.js" %}"></script>
    <script type="text/javascript"
            src="{% static "js/jquery-ui-1.8.4.js" %}"></script>
    <script type="text/javascript"
            src="{% static "js/jquery.uniform.min.js" %}"></script>
    <script type="text/javascript"
            src="{% static "js/jquery.formset.js" %}"></script>
    <script type="text/javascript"
            src="{% static "js/jquery.dataTables.min.js" %}"></script>
    <!--
    -->
    <script type="text/javascript"
            src="{% static "js/angular.min.js" %}"></script>
    <script type="text/javascript"
            src="{% static "js/mask.js" %}"></script>
    <script type="text/javascript"
            src="{% static "js/sitescript.js" %}?build=20141111"></script>
    <script type="text/javascript"
            src={% static "js/storage/operations.js" %}></script>
    <script type="text/javascript"
            src="{% static "preloader.js" %}"></script>

    {% block specific_css %}{% endblock %}
    {% block specific_js_scripts %}{% endblock %}
    {% block extra_head %}{% endblock %}
    <title>Архивист Проф</title>
</head>

<body style="overflow: hidden;">
{% load i18n %}

<div id="container">
    <div id="header">
        <a href="{% url 'homepage' %}" id="logo" class="fixThis"></br></br></a>

        {% if LICENSE %}
        <div class="right">
            <span class="userInfo">
              <span class="dateTime">
                {% now "j-M-y H:i T" %}
              </span>
              &nbsp;
              &nbsp;
              &nbsp;
              <strong>
                {{ user }} [{{ user.id }}:{{ user.arcuser.role }}]
              </strong>
              {% if user.is_authenticated %}
            </span>

            <script type="text/javascript">
              function goto_logout() {
                window.location = "/logout/?path=" + document.location.pathname;

              }
            </script>
                <div class="button">
                  <form enctype="application/x-www-form-urlencoded" method="POST" action="/logout/?path={{ request.path }}">
                    <table>
                        <!--input type="button" value="Выйти" onClick="goto_logout()"/-->
                        <input type="submit" value="Выйти"/>
                    </table>
                  </form>
                </div>
                {% endif %}
            <div class="clear"></div>
        </div>
        {% endif %}
        <div class="clear"><!--//--></div>
    </div>

{% block main %}
    {% if LICENSE or 'reports' in request.path %}
        {% if user.is_authenticated %}
            <div id="wrapper" style="overflow:hidden;">

              <div id="menuLeft" style="float:left; background: grey; width: 20%;">
                  {% include 'homepage/left_menu.html' %}
              </div>

              <div id="cont" style="margin-left: 21%; ">
                  <div class="content">
                      {% block content %}{% endblock %}
                  </div>
              </div>

              <div class="clear"></div>
            </div>
        {% else %}
            <script type="text/javascript">
              function goto_login() {
                window.location = "/login/";
              }
            </script>

            <div class="button">
              <form enctype="application/x-www-form-urlencoded" action="/login/" method="GET" >
                    <input type="button" value="Войти" onClick="goto_login()"/>
              </form>
              <noscript>
                <a href="/login/">Войти
                </a>
              </noscript>
            </div>

            <br/>
            <br/>
        {% endif %}
    {% else %}
        <center>
        <h3 class="error">Приложение не лицензировано</h3>
        <br/>
        <br/>

        <div ng-app="archivistapp" class="wrapper ng-scope" id="archivistapp_wrap" ng-controller="TaskCtrl">
        <form id="license_add" action="{% url 'users:license_create' %}" method="post">
            {% csrf_token %}
            <input type="text" ng-model="name3" clean="true" name="license" id="license" maxlength=20 ui-mask="****-****-****-****-****" style="text-transform: uppercase;" autofocus/>
            <!--
            placeholder="Ввести код лицензии"/>
            -->
            <div class="button">
                <input type="submit" value="Подтвердить">
            </div>
        </form>
        </div>
        </center>

        <br/>
        <br/>
    {% endif %}
{% endblock %}

<div id="message_panel" style="height: 5vh;">
</div>

{% include 'homepage/base_footer.html' %}
</div>

{% block endofbody %}{% endblock %}
</body>
</html>

archive/homepage/templates/homepage/base_footer.html
{% load i18n static %}
<!--footer id='footer' style="width: 100%; height: 1px; position: absolute; right: 0; bottom: 0; background: grey"-->
<footer id='footer'>
    <!--
    <p>Панель управления
    {% if user.username == 'админ' %}
      {% if perms.auth.add_session %}
        {{ perms.auth.add_session }}
      {% else %}
      {% endif %}
    {% endif %}
    -->
  {% if 'itemin' in request.path and not 'create' in request.path %}
  {% elif 'itemout' in request.path and not 'create' in request.path %}
  {% endif %}
</footer>

archive/homepage/templates/homepage/base_header.html
{% load i18n static %}
{% url 'homepage' as url_homepage %}
<header id="header">
    <div class="wrapper">
        <div id="right-side">
            <div id="top-bar">
                <div id="user-nav">
                    {% if user.is_authenticated %}
                        <a href="{% url 'control_panel:dashboard' %}">
                            {% blocktrans with login=user.username %}Go to CP ({{ login }}){% endblocktrans %}
                        </a>
                        <a href="{% url 'logout' %}">
                            {% trans "Sign out" %}
                        </a>
                    {% else %}
                        <a id="login-link" href="#sign_in"><i class="icon icon-lock">&nbsp;</i><span>{% trans "sign in" %}</span></a>
                        <a href="{% url 'create_account' %}">{% trans "Create new account" %}</a>
                        <div id="login-form" class="form">
                            <form enctype="application/x-www-form-urlencoded" method="POST" action="{% url 'login' %}">
                                {% csrf_token %}
                                <div>
                                    <a class="close-btn" href="#"></a>
                                    <div class="clear"></div>
                                </div>
                                <div class="row">
                                    <input type="text" name="username" placeholder="{% trans "Login" %}" style="color: rgb(0, 0, 0);">
                                </div>
                                <div class="row">
                                    <input type="password" name="password" placeholder="{% trans "Password" %}">
                                </div>
                                <div class="row">
                                    <input type="submit" value="{% trans "Log in" %}">
                                </div>
                            </form>
                        </div>
                        {% endif %}
                </div>
                <div class="clear"></div>
            </div>
        </div>
    </div>
</header>

archive/homepage/templates/homepage/error.html
{% extends "homepage/base.html" %}
{% load i18n static %}

{% block content %}
    <div class="error-container">
        <h1>{% block error_title %}{% endblock %}</h1>
        {% block error_content %}{% endblock %}
        <a href="{% url 'homepage' %}"><img class="error-img" src="{% static "img/404-img.png" %}"></a>
    </div>
    {% if PRODUCTION %}{% include "yandex-metrika.html" %}{% endif %}
{% endblock %}

archive/homepage/templates/homepage/field.html
{% load crispy_forms_field %}

{% if field.is_hidden %}
    {{ field }}
{% else %}
{%  if field|is_checkbox %}
    {{ field }}
    <label for="{{ field.id_for_label }}">{{ field.label }}:{% if field.field.required %}*{% endif %}</label>
{% else %}
    <label for="{{ field.id_for_label }}">{{ field.label }}:{% if field.field.required %}*{% endif %}</label>
    {{ field }}
{% endif %}
    {% if field.errors %}
        <div for="id_{{ field.id_for_label }}" class="error">{{ field.errors }}</div>
    {% endif %}
    {% if field.help_text %}
        <span>{{ field.help_text }}</span>
    {% endif %}
{% endif %}

archive/homepage/templates/homepage/homepage.html
{% extends "homepage/base.html" %}
{% load i18n static %}

{% block meta_tags %}
{% endblock %}

{% block body_attr %} class="home" {% endblock body_attr %}

{% block content %}
<section class="page-section vector-bg">
    <h3>Главная</h3>
    <div class="wrapper">
    </div>
</section>
<section class="page-section vector-bg">
{% endblock %}

archive/homepage/templates/homepage/left_menu.html
{% extends 'homepage/left_menu_block.html' %}
{% load i18n %}
{% block left_side_item %}

<div id="wrapper-200a">
  <ul class="accordion">
   <li id="one" class="subaccordion0">
     <section class="superbox">
       <label class="box-supertitle" >Перемещение единиц хранения</label>
     </section>
   </li>
   
   <li id="two" class="subaccordion1">
     <input type="radio" name="accordeon" id="sa1">
     <section class="box">
       <label class="box-title" for="sa1">Перемещение единиц хранения</label>
       <label class="box-close" for="close"></label>
     </section>
    <ul class="sub-menu sa1">
      <li><a href="/storage/client/"><em>01</em>Группы<span>{{ em }}</span></a></li>
      <li><a href="/storage/item/"><em>02</em>Единицы хранения<span>{{ em }}</span></a></li>
      <li><a href="/storage/document/"><em>03</em>Документы<span>{{ em }}</span></a></li>
      <li><a href="/storage/my_issued_items/"><em>04</em>Мои выданные единицы<span>{{ em }}</span></a></li>
    </ul>
   </li>
   
   {% if user.arcuser.role|stringformat:"i" in '1,2,3'|slice:',' %}

   <li id="three" class="subaccordion2">
     <input type="radio" name="accordeon" id="sa2">
     <section class="box">
       <label class="box-title" for="sa2">Задачи</label>
       <label class="box-close" for="close"></label>
     </section>
    <ul class="sub-menu sa2">
      <li><a href="/storage/itemout/"><em>01</em>Выдача<span>{{ em }}</span></a></li>
      <li><a href="/storage/itemin/"><em>02</em>Возврат / Размещение<span>{{ em }}</span></a></li>
    </ul>
   </li>

   {% endif %}
   
   {% if user.arcuser.role|stringformat:"i" in '1,2,3,4'|slice:',' %}

   <section class="superbox">
     <label class="box-supertitle">Система</label>
   </section>

   {% endif %}

   {% if user.arcuser.role|stringformat:"i" in '1'|slice:',' %}

   <li id="five" class="subaccordion4">
     <input type="radio" name="accordeon" id="sa4">
     <section class="box">
       <label class="box-title" for="sa4">Справочники</label>
       <label class="box-close" for="close"></label>
     </section>
    <ul class="sub-menu sa4">
      <li><a href="/storage/department/"><em>01</em>Отдел<span>{{ em }}</span></a></li>
      <li><a href="/storage/rack/"><em>02</em>Ряды<span>{{ em }}</span></a></li>
      <li><a href="/storage/client_type/"><em>03</em>Тип группы<span>{{ em }}</span></a></li>
      <li>
      <a href="/storage/rackgroup/"><em>04</em>Мобильные группы</a>
      </li>
      <li><a href="/storage/item_type/"><em>05</em>Тип единицы хранения<span>{{ em }}</span></a></li>
      <li><a href="/storage/document_type/"><em>06</em>Тип документа<span>{{ em }}</span></a></li>
      <li><a href="/storage/retention_policies/"><em>07</em>Периоды хранения<span>{{ em }}</span></a></li>
    </ul>
   </li>

   <li id="six" class="subaccordion5">
     <input type="radio" name="accordeon" id="sa5">
     <section class="box">
       <label class="box-title" for="sa5">Авторизация</label>
       <label class="box-close" for="close"></label>
     </section>
    <ul class="sub-menu sa5">
      <li><a href="/users/"><em>01</em>Пользователи</a></li>
    </ul>
   </li>
   {% endif %}

   {% if user.arcuser.role|stringformat:"i" in '1,2,4'|slice:',' %}
   <li id="seven" class="subaccordion6">
     <input type="radio" name="accordeon" id="sa6">
     <section class="box">
       <label class="box-title" for="sa6">Отчеты</label>
       <label class="box-close" for="close"></label>
     </section>
    <ul class="sub-menu sa6">
      <li><a href="{% url 'reports:rem-items' %}"><em>01</em>По уничтожаемым единицам</a></li>
      <li><a href="{% url 'reports:storage-items'%}"><em>02</em>По единицам хранения</a></li>
    </ul>
   </li>
   {% endif %}

   <section class="superbox">
     <label class="box-supertitle">Настройки</label>
   </section>

   <li id="eight" class="subaccordion7">
     <input type="radio" name="accordeon" id="sa7">
     <section class="box">
       <label class="box-title" for="sa7">Мои Настройки</label>
       <label class="box-close" for="close"></label>
     </section>
     {% if user.arcuser.role|stringformat:"i" in '1'|slice:',' %}
        <ul class="sub-menu sa7">
          <li><a href="/users/profile/{{ user.id }}"><em>01</em>Мой профиль</a></li>
          <li><a href="/storage/settings/"><em>01</em>Системные</a></li>
        </ul>
     {% else %}
        <ul class="sub-menu sa8">
          <li><a href="/users/profile/{{ user.id }}"><em>01</em>Мой профиль</a></li>
        </ul>
     {% endif %}
   </li>
     <input type="radio" name="accordeon" id="close">
  </ul>
  
 </div>

{% endblock %}

archive/homepage/templates/homepage/left_menu_block.html
<div class="blockGrey side">
    <div class="top">
        <div class="bot">
            <div class="content">
                {% block left_side_item %}
                {% endblock %}
            </div>
        </div>
    </div>
</div>