archive/urls.py
# coding: utf-8

from django.contrib.auth.views import logout, login
from django.contrib import admin
from django.conf.urls import include, url
from .utils.decorators import anonymous_required
from archive.users.views import arc_login, arc_logout

urlpatterns = [
    url(r'^admin/', admin.site.urls),
]

urlpatterns += (
    url(r'^storage/', include('archive.storage.urls', namespace="storage")),
    url(
        r'^login/$',
        anonymous_required(login),
        {'template_name': "homepage/registration/login.html"},
        name="login",
    ),
    url(
        r'^arc_login/$',
        arc_login,
        name="arc_login",
    ),
    url(r'^logout/$', arc_logout, name="logout"),
    url(r'^api/', include('archive.api.urls', namespace="api")),
    url(r'^users/', include('archive.users.urls', namespace="users")),
    url(r'^reports/', include('archive.reports.urls', namespace='reports')),
    url(r'^', include('archive.homepage.urls')),
    url(r'^', include('archive.homepage.urls', namespace="registration_complete")),
)

archive/users/urls.py
# coding: utf-8
from django.conf.urls import include, url
from django.views.generic import TemplateView
from archive.users.views import ARCRegistrationView, exec_rule, license, UserCreate, UserChangePassword, UserEdit, UserDelete, UserList, UserDocs

urlpatterns = (
    url(r'^$', UserList.as_view(), name='users'),
    url(r'^docs/', UserDocs.as_view(), name='user_search'),
    url(r'^register/$', ARCRegistrationView.as_view(), name='register'),
    url(r'^create/$',
        UserCreate.as_view(), name='create'),

    url(r'^exec_rule/(?P<rule>\d+)/$',
        exec_rule, name='exec_rule'),
    url(r'^profile/(?P<pk>\d*)?',
        UserList.as_view(), name='user_profile'),
    url(r'^change_password/(?P<pk>\d+)/$',
        UserChangePassword.as_view(), name='change_password'),
    url(r'^edit/(?P<user>\d+)/(?P<pk>\d+)/$',
        UserEdit.as_view(), name='user_edit'),
    url(r'^delete/(?P<pk>\d+)/$',
        UserDelete.as_view(), name='user_delete'),
    url(r'^license/create/$',
        license, name='license_create'),
)

archive/users/models.py
# -*- coding: utf-8 -*-

import inspect
from django.db import models, transaction
from django.contrib.auth.models import User as DefaultUser, Group
from django.db.models import Manager
from django.utils.translation import ugettext_lazy as _
from django.dispatch import receiver
from django.db.models.signals import post_save
from archive.storage.models import Department
from django.conf import settings

from archive.utils.models import TimeStampedModelIndexed, BaseParameter
from registration.models import RegistrationManager

USER_ROLE = (
    (0, u'Не авторизован'),
    (1, u'Администратор'),
    (2, u'Архивариус'),
    (3, u'Оператор'),
    (4, u'Редактор'),
    (5, u'Пользователь'),
)

class Customer(TimeStampedModelIndexed):
    name = models.CharField(_(u'Имя'), max_length=100)

    def __unicode__(self):
        return '%s %s' % (self.created, self.name)

class ArcUser(TimeStampedModelIndexed):
    user = models.OneToOneField(DefaultUser, null=True, default=None)
    role = models.PositiveSmallIntegerField(
        choices=USER_ROLE,
        default=0,
        blank=True, null=True,
    )
    department = models.ForeignKey(Department,
                                   on_delete=models.SET_NULL,
                                   blank=True, null=True,
                                   verbose_name=_(u'Отдел'))
    send_command = models.PositiveSmallIntegerField(
        default=1,
        verbose_name=_(u'Выполнять')
    )
    last_url = models.CharField(_(u'Наименование'), max_length=512, default='/storage/item/',
                                   blank=True, null=True,
            )

    search = models.TextField(_(u'Поиск'), null=True, blank=True)

    def create_index(self):
        search = ''
        try:
            if self.user.username:
                search = search + self.user.username.replace(' ', '')
            if self.user.first_name:
                search = search + self.user.first_name.replace(' ', '')
            if self.user.last_name:
                search = search + self.user.last_name.replace(' ', '')
            if self.user.is_active:
                search = search + 'Активен'
            else:
                search = search + 'Не активен'
            if self.role:
                role = [r for r in USER_ROLE if str(r[0]) == str(self.role)]
                if role and len(role) > 0 and len(role[0]) > 1:
                    search = search + role[0][1]
            if self.department:
                search = search + self.department.__str__().replace(' ' , '') 
        except Exception as e:
            print("LOG: %s %s ERROR: %s" % (self.__class__, inspect.stack()[0][3].upper(), e))
            pass

        if search and len(search) > 1:
            self.search = search.lower().replace(' ' , '')
        else:
            self.search = ''

        if settings.DEBUG_MESSAGES:
            print("LOG: %s SEARCH: %s" % (self.__class__, self.search))
        return self.search

    def save(self, *args, **kwargs):
        self.create_index()
        super(self.__class__, self).save(*args, **kwargs)

    def set_role(self, role=None):
        if not role:
            self.role = 0
            return
        valid_items = [item for item in USER_ROLE if str(item[0]) == str(role)]

        if valid_items and len(valid_items):
            self.role = role

            if 1 == role:
                self.last_url = '/users/'
                self.save(update_fields=['last_url'])
        else:
            self.role = 0
        self.save(update_fields=['role', 'search'])

    def get_role_name(self):
        return '%s' % ([r for r in USER_ROLE if str(r[0]) == str(self.role)][0][1])

    def __unicode__(self):
        return '%s' % (self.user.username)

    @receiver(post_save, sender=DefaultUser)
    def create_user_user(sender, instance, created, **kwargs):
        print("LOG: INSTANCE", instance, "CREATED:", created, "KWARGS:", kwargs)
        if created:
            user = ArcUser.objects.filter(user=instance)
            if instance:
                print("LOG: INSTANCE USER")
                u = ArcUser.objects.create(user=instance, role=0)

    class Meta:
        permissions = [
            ("user.edit", _("Редактирование пользователей")),
        ]

class License(TimeStampedModelIndexed):
    code = models.CharField(_(u'Код'), max_length=100)

    def __unicode__(self):
        return '%s' % (self.created)

archive/users/views.py
# -*- coding: utf-8 -*-

import inspect
from django.utils.http import urlencode
from django.core.exceptions import ValidationError
from django.views.generic import DeleteView, ListView, UpdateView, DetailView
from django.core.management.base import BaseCommand
from django.core.urlresolvers import reverse_lazy
from django.views.generic.base import TemplateView
from django.http import HttpResponse, HttpResponseRedirect
from registration.backends.default.views import RegistrationView as BaseRegistrationView
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User as DefaultUser, Group
from django.views.generic import CreateView, DetailView

from os.path import join as pathjoin
from archive.utils.decorators import anonymous_required, allow_access, set_created, set_modified
from archive.utils.helpers import reverse_absolute_uri, get_remote_addr, djqs_from_search
from archive.users.models import License, ArcUser
from archive.storage.models import Item, Document
from .forms import UserChangePasswordForm, DeleteUserForm, UserEditForm, UserCreateForm


def arc_login(request):
    users = ArcUser.objects.filter(user=request.user)

    if users and users.exists():
        user_path = users.last().last_url
        print ("LOG: arc_login USERS_PATH:", user_path)
        return HttpResponseRedirect(user_path)
    return HttpResponseRedirect("/")

def arc_logout(request):
    path = request.GET.get('path', None)
    user_path = None
    users = ArcUser.objects.filter(user=request.user)

    if users and users.exists():
        user = users.last()
        user.last_url = path
        user.save(update_fields=['last_url'])
        user_path = user.last_url

    print ("LOG: request arc_logout", "PATH:", path, "USERS_PATH:", user_path)
    logout(request)
    return HttpResponseRedirect("/")


def exec_rule(request, rule):
    if request.method != 'GET':
        return HttpResponseRedirect("/")
    print("LOG: EXEC_RULE: GET:", rule)
    remote_addr = get_remote_addr(request)
    user = None

    try:
        user = ArcUser.objects.get(user=request.user)
    except Exception as e:
        return HttpResponse({'status': 'ERROR', 'remote_addr': remote_addr, 'message': 'Авторизованный пользователь не найден'}, status=201)

    if not user:
        print("LOG: EXEC_RULE: GET:", rule)
        return HttpResponse({'status': 'ERROR', 'remote_addr': remote_addr, 'message': 'Авторизованный пользователь не найден'}, status=201)

    try:
        user.send_command = int(rule)
        user.save(update_fields=['send_command'])
    except Exception as e:
        return HttpResponse({'status': 'ERROR', 'remote_addr': remote_addr, 'message': 'Авторизованный пользователь не найден'}, status=201)
    print("LOG: EXEC_RULE: OK")
    return HttpResponse({'uuid': {'value': 'OK'}})

def license(request):
    llist = ['11111111111111111111']
    if request.method != 'POST':
        return HttpResponseRedirect("/")
    print("LOG: LICENSE: POST:", request.POST)
    try:
        code = request.POST.get('license', '')
    except Exception as e:
        return HttpResponseRedirect("/")
    code = code.replace('-', '').replace(' ' , '')

    if code and len(code) > 0 and code in llist:
        License.objects.create(code=code)

    return HttpResponseRedirect("/")


class UserCreate(CreateView):
    model = DefaultUser
    form_class = UserCreateForm
    template_name = 'users/create.html'
    success_url = reverse_lazy('users:users')

    def get_context_data(self, **kwargs):
        context = super(self.__class__, self).get_context_data(**kwargs)
        context['action'] = u'Создать пользователя'
        return context

    @allow_access([1], 'users:users')
    def post(self, request, *args, **kwargs):
        post = super(self.__class__, self).post(request, *args, **kwargs)
        print('LOG: %s "%s": %s' % (self.__class__, inspect.stack()[0][3], request.POST))
        try:
            name = request.POST.get('username', '')
            new_user = ArcUser.objects.filter(user__username=name).first()
            if new_user:
                new_user.search = ''
                new_user.save(update_fields=['search'])
        except Exception as e:
            print('      LOG: %s "%s" ERROR: %s' % (self.__class__, inspect.stack()[0][3], e))
        return post

class UserList(ListView):
    model = ArcUser
    template_name = 'users/list.html'
    pk = None

    def get_queryset(self):
        if 'pk' in self.kwargs:
            self.pk = self.kwargs['pk']

        users = ArcUser.objects.filter(user=self.request.user)

        if users and users.exists() and users.last().role in [1]:
            pass
        else:
            if not self.pk or (self.pk and self.pk != self.request.user.id):
                self.pk = self.request.user.id
                print("LOG: USER: ", str(self.__class__), "GETUSER_ROLE:", users.last().role, " FORCE PK:", self.pk)

        if self.pk:
            return DefaultUser.objects.filter(pk=self.pk).order_by('arcuser__role', 'id')
        else:
            return DefaultUser.objects.all().select_related('arcuser').order_by('arcuser__role', 'id')

    @allow_access([1, 2, 3, 4, 5])
    def get(self, request, *args, **kwargs):
        return super(UserList, self).get(request, *args, **kwargs)

class UserEdit(UpdateView):
    model = DefaultUser
    template_name = 'users/create.html'
    form_class = UserEditForm
    success_url = reverse_lazy('users:users')

    @allow_access([1], 'users:users')
    def post(self, request, *args, **kwargs):
        return super(UserEdit, self).post(request, *args, **kwargs)

    def get_initial(self):
        pk = self.kwargs['pk']
        curr_user = self.kwargs['user']
        currusers = ArcUser.objects.filter(user__pk=curr_user)
        arcusers = ArcUser.objects.filter(user__pk=pk)

        if arcusers and arcusers.exists() and currusers and currusers.exists():
            return { 'role': arcusers.first().role,
                     'curr_role': currusers.first().role,
                   }

class UserChangePassword(UpdateView):
    model = DefaultUser
    template_name = 'users/change_password.html'
    form_class = UserChangePasswordForm
    success_url = reverse_lazy('users:users')

    @allow_access([1], 'users:users')
    def post(self, request, pk, *args, **kwargs):
        passw1 = request.POST.get('new_password1', None)
        passw2 = request.POST.get('new_password2', None)

        if passw1 and passw2 and passw1 == passw2:
            users = DefaultUser.objects.filter(pk=pk)
            if users and users.count() == 1:
                user = users[0]
                user.set_password(passw1)
                user.save()
            else:
                error_message = u'Ошибка смены пароля, пользователь не найден'
                return HttpResponseRedirect(reverse_lazy('users:change_password', args=(pk, )) + '?%s' % urlencode({'error': error_message}))
        else:
            error_message = u'Ошибка смены пароля, пароли не совпадают'
            return HttpResponseRedirect(reverse_lazy('users:change_password', args=(pk, )) + '?%s' % urlencode({'error': error_message}))
        return HttpResponseRedirect(self.success_url)

    def form_invalid(self, form):
        error_message = ''
        err_json = json.loads(form.errors.as_json())
        print("LOG:", err_json)

        error_message = err_json
        return HttpResponseRedirect(reverse_lazy('users:change_password') + '?%s' % urlencode({'error': error_message}))

    def get_context_data(self, **kwargs):
        context = super(UserChangePassword, self).get_context_data(**kwargs)
        context['error_message'] = self.request.GET.get('error', '')
        return context

class UserDelete(DeleteView):
    model = DefaultUser
    template_name = 'users/delete.html'
    form_class = DeleteUserForm
    success_url = reverse_lazy('users:users')

    @allow_access([1], 'users:users')
    def post(self, request, *args, **kwargs):
        return super(UserDelete, self).post(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(UserDelete, self).get_context_data(**kwargs)

        # check presense before deletion
        pk = self.kwargs.get('pk', None)

        if pk:
            exists = Document.objects.filter(owner=pk).exists()
            if exists:
                context['error_message'] = u'Удаляемый пользователь используется в документе'
            exists = Item.objects.filter(owner=pk).exists()
            if exists:
                context['error_message'] = u'Удаляемый пользователь используется в ЕХ'
        return context

class Command(BaseCommand):
    from django.http import HttpRequest

    help = "Read all available users and all available not expired sessions. Then logout from each session."

    def handle(self, **options):
        now = django.utils.timezone.now()
        request = HttpRequest()

        sessions = Session.objects.filter(expire_date__gt=now)

        print(('LOG: Found %d not-expired session(s).' % len(sessions)))

        for session in sessions:
            username = session.get_decoded().get('_auth_user_id')
            request.session = self.init_session(session.session_key)

            logout(request)
            print(('LOG: Successfully logout %r user.' % username))

        print('LOG: All OK!')

    @staticmethod
    def init_session(session_key):
        """
        Initialize same session as done for ``SessionMiddleware``.

        engine = import_module(settings.SESSION_ENGINE)
        return engine.SessionStore(session_key)
        """

class RegistrationDisallowedView(TemplateView):
    def get_template_names(self):
        if 'account_type' in self.kwargs:
            return pathjoin('registration/complete/', self.kwargs['account_type'] + '.html')
        else:
            return super(RegistrationDisallowedView, self).get_template_names()

archive/users/templates/users/change_password.html
{% extends "homepage/base.html" %}
{% load helper_tags i18n static %}

{% block meta_tags %}
{% endblock %}

{% block content %}
<section class="page-section vector-bg">
  <h3 class="title">Изменить пароль</h3>
  {% if error_message %}
  <br/>
  <div class="error">{{ error_message }}</div>
  {% endif %}
  <br/>

  {% if form %}
      <form method="POST" action=".">
          {% csrf_token %}
          <fieldset>
              {{ form|as_form }}
              <div class="clear"></div>
          </fieldset>
          <br/>
          <div class="button">
            <input type="submit" value="{% trans "Save" %}">
          </div>
          <div class="clear"><!--//--></div>
      </form>
  {% endif %}
</section>
{% endblock %}

archive/users/templates/users/create.html
{% extends "homepage/base.html" %}
{% load helper_tags i18n static %}

{% block meta_tags %}
{% endblock %}

{% block content %}
<section class="page-section vector-bg">
  {% if action %}
    <h3 class="title">{{ action }}</h3>
  {% else %}
    <h3 class="title">Редактирование пользователя</h3>
  {% endif %}
  {% if error_message %}
  <br/>
  <div class="error">{{ error_message }}</div>
  {% endif %}
  <br/>

  {% if form %}
      <form method="POST" action=".">
          {% csrf_token %}
          <fieldset>
              {{ form|as_form }}
              <div class="clear"></div>
          </fieldset>
          <br/>
          <div class="button">
            <input type="submit" value="{% trans "Save" %}">
          </div>
          <div class="clear"><!--//--></div>
      </form>
  {% endif %}
</section>
{% endblock %}

archive/users/templates/users/delete.html
{% extends "homepage/base.html" %}

{% block page_title %}Удалить стеллаж{{ object }}{% endblock %}

{% block content %}
<form method="POST" action=".">
        {% csrf_token %}
        <fieldset>
          <legend>Удалить ?</legend>
          </br>
          <div class="button">
            <input type="submit" name="yes" value="Да.Удалить"/>
          </div>
        </fieldset>

    </form>
{% endblock %}

archive/users/templates/users/details.html
    <table cellspacing="0" class="stdAppTable">
        <tr>
            <th>Пользователь</th>
            <th>Имя</th>
            <th>Фамилия</th>
            <th>Статус</th>
            <th>Роль</th>
            <th>Отдел</th>
            <th></th>
        </tr>

        {% for user in object_list %}
            {% if user.username %}
            <tr class="{% cycle 'odd' 'even' %}" id="{{ user.id }}">
              <td>{{ user.username }}</td>
              <td>{{ user.first_name }}</td>
              <td>{{ user.last_name }}</td>
              <td>
                  {% if user.is_active %}
                    Активен
                  {% else %}
                    Не активен
                  {% endif %}
              </td>
              <td>{{ user.arcuser.get_role_name }}</td>
              <td>
                  {% if user.arcuser.department %}
                    {{ user.arcuser.department }}
                  {% endif %}
              </td>
              <td class="controls">
                  <a class="bt-edit" href="{% url 'users:change_password' user.id %}">
                     Сменить пароль
                  </a>
                  <a class="bt-edit" href="{% url 'users:user_edit' request.user.id user.id %}">
                     Изменить
                  </a>
                  <a class="bt-edit" href="{% url 'users:user_delete' user.id %}">
                     Удалить
                  </a>
              </td>
            </tr>
            {% endif %}
        {% endfor %}
    </table>

archive/users/templates/users/field.html
{% load crispy_forms_field %}

{% if field.is_hidden %}
    {{ field }}
{% else %}
{%  if field|is_checkbox %}
    {{ field }}
    <label for="{{ field.id_for_label }}">{{ field.label }}:{% if field.field.required %}*{% endif %}</label>
{% else %}
    <label for="{{ field.id_for_label }}">{{ field.label }}:{% if field.field.required %}*{% endif %}</label>
    {{ field }}
{% endif %}
    {% if field.errors %}
        <div for="id_{{ field.id_for_label }}" class="error">{{ field.errors }}</div>
    {% endif %}
    {% if field.help_text %}
        <span>{{ field.help_text }}</span>
    {% endif %}
{% endif %}

archive/users/templates/users/list.html
{% extends "homepage/base.html" %}
{% load static pagination_tags helper_tags i18n %}

{% block breadcrumbs %}
  {{ block.super }}
{% endblock %}

{% block content %}

  <script type="text/javascript">
    $(function() {
    $('#add').submit(function() {
    $.post("{% url 'users:create' %}", function() {
    window.location = "{% url 'users:create' %}";
    });
    return false;
    });
    });
  </script>
  <div ng-app="archivistapp" class="wrapper ng-scope iterfaces" id="form_wrap" ng-controller="TaskCtrl">

    {% if not 'profile' in request.path %}
    <div style=";">
      <div style="width:50%;float:left;display:inline-block;">
        <h3 class="title">Пользователи</h3>
      </div>
      <div style="margin-left:50%;">
        <span style="display: block;overflow: hidden;">
          <input id="search" type="text" title="search" style="width: 100%;" placeholder="Искать" ng-keyup="user_keyup($event.which)" autofocus /></span>
      </div>
    </div>
    {% endif %}

    {% if error_message %}
      <br/>
      <div class="error">{{ error_message|safe }}</div>
    {% endif %}
    <br/>
    <br/>

    <!--
        % include "utils/filters/toggled_format_filter.html" %}
        % paginate %}
      -->
    {% if not 'profile' in request.path %}
      <div class="button">
        <form method="POST" name="add" id="add" action =".">
          <input type="submit" value="Создать новый"/>
        </form>
        <noscript>
          <a href="{% url 'users:create' %}">
            Создать
          </a>
        </noscript>
      </div>
    {% endif %}
    <br/>
    <br/>

    <div id="user_details">
      {% include 'users/details.html' %}
    </div>
  </div>
  <!--
      % paginate %}
    -->
  {% endblock %}