archive/reports/urls.py
# coding: utf-8

from django.contrib.auth.views import logout, login
from django.contrib import admin
from django.conf.urls import include, url
from .views import OutTasksPDF, InTasksPDF, StorageItemsPDF, RemovableItemsPDF, StorageItemsReport, RemovableItemsReport

urlpatterns = (
    url(r'^removable_items/$', RemovableItemsReport.as_view(), name='rem-items'),
    url(r'^storage_items/$', StorageItemsReport.as_view(), name='storage-items'),
    url(r'^removable_items_pdf/$', RemovableItemsPDF.as_view(), name='removable-items-pdf'),
    url(r'^storage_items_pdf/$', StorageItemsPDF.as_view(), name='storage-items-pdf'),
    url(r'^intasks_pdf/$', InTasksPDF.as_view(), name='intasks_pdf'),
    url(r'^outtasks_pdf/$', OutTasksPDF.as_view(), name='outtasks_pdf'),
)

archive/urls.py
# coding: utf-8

from django.contrib.auth.views import logout, login
from django.contrib import admin
from django.conf.urls import include, url
from .utils.decorators import anonymous_required
from archive.users.views import arc_login, arc_logout

urlpatterns = [
    url(r'^admin/', admin.site.urls),
]

urlpatterns += (
    url(r'^storage/', include('archive.storage.urls', namespace="storage")),
    url(
        r'^login/$',
        anonymous_required(login),
        {'template_name': "homepage/registration/login.html"},
        name="login",
    ),
    url(
        r'^arc_login/$',
        arc_login,
        name="arc_login",
    ),
    url(r'^logout/$', arc_logout, name="logout"),
    url(r'^api/', include('archive.api.urls', namespace="api")),
    url(r'^users/', include('archive.users.urls', namespace="users")),
    url(r'^reports/', include('archive.reports.urls', namespace='reports')),
    url(r'^', include('archive.homepage.urls')),
    url(r'^', include('archive.homepage.urls', namespace="registration_complete")),
)

archive/api/models.py
# -*- coding: utf-8 -*-

from django.contrib.auth.models import User as DefaultUser, Group
from django.db import models
from django.utils.translation import ugettext_lazy as _
from archive.utils.models import TimeStampedModelIndexed
from archive.users.models import Customer
from archive.storage.models import Item
from django.conf import settings

MISSION_STATUS = (
    ('debug', 'Отладка'),
    ('inprogress', 'Выполняется'),
    ('done', 'Выполнена'),
)

MISSION_NAME = (
    ('IN', 'Прием'),
    ('OUT', 'Выдача'),
    ('REMOVE', 'Уничтожение'),
    ('DEFRAG', 'Дефрагментация'),
)

class Mission(TimeStampedModelIndexed):
    name = models.CharField(
        _('Задание'), max_length=20,
        choices=MISSION_NAME,
        blank=True, null=True,
    )
    owner = models.ForeignKey(DefaultUser,
                null=True, blank=True,
                on_delete=models.SET_NULL,
                verbose_name=_(u"Архивариус")
    )
    status = models.CharField(
        _('Состояние'), max_length=20,
        choices=MISSION_STATUS,
        blank=True, null=True,
    )

    def __str__(self):
        return '"%s" %s' % ([name for name in MISSION_NAME if name[0] == self.name][0][1], self.owner)

    def __unicode__(self):
        return '%s %s %s' % (self.name, self.owner, self.created)

    class Meta:
        verbose_name = _('Операция')
        verbose_name_plural = _('Операции')
        ordering = ['created']


class Task(TimeStampedModelIndexed):
    command = models.CharField(
        _('Команда'), max_length=20,
        blank=True, null=True,
    )
    status = models.CharField(
        _('Состояние'), max_length=20,
        choices=MISSION_STATUS,
        blank=True, null=True,
    )
    item = models.ForeignKey(Item, blank=True, null=True)
    mission = models.ForeignKey(Mission, models.CASCADE)
    owner = models.ForeignKey(DefaultUser,
                              null=True, blank=True,
                              on_delete=models.SET_NULL,
                              verbose_name=_(u"Выдан"))
    description = models.CharField(_(u'Комментарий'), max_length=1024, null=True, blank=True)

    search = models.TextField(_(u'Поиск'), null=True, blank=True)

    def create_index(self):
        if self.mission and self.mission.status == 'done':
            return
        search = ''
        if self.item:
            search = search + self.item.number.replace(' ', '')
            search = search + self.item.name.replace(' ', '')
        if self.description:
            search = search + self.description.replace(' ', '')
        if self.item and self.item.slot_set:
            if self.item.slot_set.all().first():
                search = search + self.item.slot_set.all().first().shelf.section.row.rack.rack_group.__str__().replace('', '')
                search = search + self.item.slot_set.all().first().shelf.section.row.__str__().replace('', '')
                search = search + self.item.slot_set.all().first().shelf.section.__str__().replace('', '')
                search = search + self.item.slot_set.all().first().shelf.__str__().replace('', '')
                search = search + self.item.slot_set.all().first().__str__().replace('', '')
        if self.owner:
            search = search + self.owner.__str__().replace(' ', '')
        search = search + self.__str__().replace(' ', '')

        if search and len(search) > 1:
            self.search = search.lower().replace(' ' , '')
        else:
            self.search = ''

        if settings.DEBUG_MESSAGES:
            print("LOG: %s SEARCH: %s" % (self.__class__, self.search))
        return self.search

    def save(self, *args, **kwargs):
        self.create_index()
        super(self.__class__, self).save(*args, **kwargs)
        self.create_index()

    def __str__(self):
        return '[%s]' % ([status for status in MISSION_STATUS if status[0] == self.status][0][1])

    def __unicode__(self):
        return 'Задача #%s [%s]' % (self.id, [status for status in MISSION_STATUS if status[0] == self.status][0][1])

    class Meta:
        verbose_name = _('Задание')
        ordering = ['created']

class License(TimeStampedModelIndexed):
    code = models.CharField(
        _('Код'), max_length=1024,
        null=True,
    )

archive/reports/models.py
# -*- coding: utf-8 -*-

from django.db import models

from django.contrib.auth.models import User as DefaultUser, Group
from archive.utils.models import TimeStampedModelIndexed

class Report(TimeStampedModelIndexed):
    user = models.ForeignKey(DefaultUser)
    fields = models.TextField(null=True, blank=True)
    remove_fields = models.TextField(null=True, blank=True)

archive/reports/views.py
# -*- coding: utf-8 -*-

import inspect
import locale
from braces.views import LoginRequiredMixin
from django.core.urlresolvers import reverse_lazy
from django.views.generic import ListView, TemplateView
from django.http import FileResponse, HttpResponse, HttpResponseRedirect
from django.views import View
from django.contrib.auth.models import Permission, User as DefaultUser, Group
from datetime import datetime
from django.db import transaction

from wkhtmltopdf.views import PDFTemplateView

from archive.reports.models import Report
from archive.api.models import Task
from archive.storage.models import Settings, RackGroup, ItemType, Department, RetentionPolicy, Item
from archive.storage.views import BaseStorage
from archive.utils.decorators import allow_access, set_created, set_modified
from archive.api.models import Task, Mission

from io import StringIO
from xhtml2pdf import pisa
from django.template.loader import get_template
from django.template import Context
from django.http import HttpResponse
from cgi import escape
from django.shortcuts import render
from django.template.loader import render_to_string


def render_to_pdf(rendered_html_name):

    with open(rendered_html_name + '.html', "r") as html_file:
        content = html_file.read()
        pdfFile = open(rendered_html_name + '.pdf', "wb")
        pdf = pisa.CreatePDF(StringIO(content), pdfFile, encoding='UTF-8', show_error_as_pdf=True)
        pdfFile.close()
        #pdf = pisa.CreatePDF(StringIO(content), pdf_file, encoding='UTF-8')
    return open(rendered_html_name + '.pdf', "rb")


class StorageItemsReport(BaseStorage, ListView):
    paginate_by = 10
    model = Item
    template_name = 'reports/storage_items.html'
    methods = ['get', 'post']
    default_fields = ['created', 'fiscal_year', 'retention_policy', 'item_type', 'department', 'rack_group', 'released_to', 'owner', 'created_by', 'description', 'name', 'client', 'number']
    contains_fields = ['created', 'fiscal_year', 'description', 'name', 'number']

    def __init__(self, **kwargs):
        super(StorageItemsReport, self).__init__(**kwargs)
        settings = Settings.objects.all().first()
        try:
            self.paginate_by = int(settings.paginate_by)
        except:
            pass

    def get_queryset(self):
        queryset = super(self.__class__, self).get_queryset().order_by('number', 'id')
        for q in self.request.GET:
            if 'topdf' == q:
                continue
            if 'page' == q:
                continue
            value = self.request.GET.get(q, None)
            filters = {}

            if value:
                if q in self.contains_fields:
                    filters[q + '__contains'] = value
                else:
                    if 'rack_group' == q:
                        q = 'slot__shelf__section__row__rack__rack_group'
                    elif 'scope' == q:
                        if value == u'На хранении':
                            q = 'released'
                            value = False
                        elif value == u'Выданные':
                            q = 'released'
                            value = True
                        else:
                            continue
                    elif 'released_to' == q:
                        q = 'task__owner__id'
                        filters['task__mission__name'] = 'OUT'
                        filters['released'] = True
                    filters[q] = value
                print("LOG: %s QUERYSET FILTER: %s" % (self.__class__, filters))
            queryset = queryset.filter(**filters)
        return queryset

    def get_objects_list(self, model):
        obj_queryset = model.objects.all()

        if obj_queryset.count() > 0:
            self.obj_list = [(str(obj.id), obj) for obj in obj_queryset]
            self.obj_list.insert(0, (-1, '-------'))
        else:
            self.obj_list = []
        self.object_list = self.obj_list
        return self.obj_list

    def post(self, request, *args, **kwargs):
        print("LOG: %s POST: %s" % (self.__class__, request.POST))
        reports = Report.objects.filter(user=request.user)
        report = None
        filters = {}

        if not reports or not reports.exists():
            my_fields = self.default_fields

            try:
                report = Report.objects.create(user=request.user, fields=my_fields)
            except Exception as e:
                print("LOG: %s POST CREATE ERROR: %s" % (self.__class__, e))
                return HttpResponseRedirect(self.get_success_url())
        else:
            report = reports.first()

            if report.fields and len(report.fields) > 2:
                try:
                    my_fields = report.fields.split(',')

                    for item in my_fields:
                        if item not in self.default_fields:
                            my_fields.remove(item)
                except Exception as e:
                    my_fields = self.default_fields
                    print("LOG: %s POST FIELDS ERROR: %s" % (self.__class__, e))
            else:
                my_fields = []

        if 'print_pdf' in request.POST:
            # TODO: refactor this to function
            for name in self.request.POST:
                if 'val_' in name:
                    field = name.replace('val_', '')
                    value = self.request.POST.get(name, None)

                    if not value or len(value) == 0 or value == '-1':
                        pass
                    else:
                        filters[field] = value

            return HttpResponseRedirect(self.get_success_url(filters, to_pdf=True))

            content = render_to_string(self.template_name, self.get_context_data())
            with open('_files/storage_report.html', "wb") as static_file:
                static_file.write(content.encode('UTF-8'))

            return FileResponse(render_to_pdf(
                                render(request, self.template_name, self.get_context_data()),#, encoding='UTF-8'),
                                user=request.user,
                                ), content_type='application/pdf')

        if 'cleanall' in request.POST:
            request.POST = {}

        if 'del_' in str(request.POST):
            for name in request.POST:
                #print("LOG: name:", name)
                if 'del_' in str(name):
                    #print("LOG: del name:", name)
                    field = str(name).replace('del_', '')
                    #print("LOG: del name:", field)

                    if field and field in my_fields:
                        my_fields.remove(field)
                    break
        elif 'add_field' in request.POST and request.POST.get('add_field', None) != '':
            field = request.POST.get('add_field', None)
            #print("LOG: %s CONTEXT FIELDS: %s FIELD: %s" % (self.__class__, my_fields, field))

            if field and not field in my_fields:
                my_fields.append(field)
        else:
            for name in self.request.POST:
                if 'val_' in name:
                    field = name.replace('val_', '')
                    value = self.request.POST.get(name, None)

                    if not value or len(value) == 0 or value == '-1':
                        pass
                    else:
                        filters[field] = value
            print("LOG: %s CONTEXT FILTERS: %s" % (self.__class__, filters))

        if report and not report.fields == ','.join(my_fields):
            report.fields = ','.join(my_fields)
            report.save(update_fields=['fields'])

        return HttpResponseRedirect(self.get_success_url(filters))

    def get_context_data(self, **kwargs):
        try:
            context = super(StorageItemsReport, self).get_context_data(**kwargs)
        except Exception as e:
            print(e)
            context = {}

        if self.request.GET.get('topdf'):
            context['REPORT'] = True
        reports = Report.objects.filter(user=self.request.user)

        if not reports or not reports.exists():
            my_fields = self.default_fields
        else:
            if reports.first().fields and len(reports.first().fields) > 2:
                try:
                    my_fields = reports.first().fields.split(',')
                except Exception as e:
                    print("LOG: %s CONTEXT_FIELDS ERROR: %s" % (self.__class__, e))
                    my_fields = self.default_fields
            else:
                my_fields = []
        print("LOG: %s CONTEXT_FIELDS: %s" % (self.__class__, my_fields))

        context['fields'] = my_fields
        context['departments'] = self.get_objects_list(Department)
        context['rack_groups'] = self.get_objects_list(RackGroup)
        context['item_types'] = self.get_objects_list(ItemType)
        context['pers'] = self.get_objects_list(DefaultUser)
        context['policies'] = self.get_objects_list(RetentionPolicy)

        return context

    def get_success_url(self, filters={}, to_pdf=False):
        query_string = ''

        for k in filters:
            if len(query_string) > 1:
                query_string = query_string + '&' + k + '=' + filters[k]
            else:
                query_string = k + '=' + filters[k]
        if to_pdf:
            query_string = query_string + '&' + 'topdf=true'
            return reverse_lazy('reports:storage-items-pdf') + '?' + query_string
        print("LOG: %s FILTER: %s" % (self.__class__, query_string))

        return reverse_lazy('reports:storage-items') + '?' + query_string

    @set_created
    def form_valid(self, form):
        try:
            response = super(self.__class__, self).form_valid(form)
        except Exception as e:
            print("LOG: %s FORM ERROR: %s" % (self.__class__, e))
            return HttpResponseRedirect(self.get_success_url())
        return response

archive/reports/templates/intasks_pdf.html
{% extends "reports/base.html" %}
{% load helper_tags i18n static %}

{% block content %}
<h1 class="title">Операции Возврата / Размещения</h1>
<br/>
<br/>

<p>Дата создания отчета: <strong>{{ report_date }}.</strong> Имя пользователя: <strong>{{ report_user }}</strong></p>
<br/>
<br/>

<table cellspacing="2" class="stdAppTable" width="100%" border="1px">
        <tr>
            <th>Регистрационный №</th>
            <th>Наименование</th>
            <th>Комментарий</th>
            <th>Мобильная группа</th>
            <th>Ряд</th>
            <th>Секция</th>
            <th>Полка</th>
            <th>Место</th>
            <th>Пользователь</th>
            <th>Статус</th>
            <th></th>
        </tr>
        {% for mission in object_list %}
            {% for task in mission.task_set.all %}
            <tr>
              {% if task.item %}
                {% with task.item as titem %}
                    <td>{{ titem.number }}</td>
                    <td>{{ titem.name|default_if_none:'' }}</td>
                    <td>{{ task.description|default_if_none:'' }}</td>

                    {% if titem.slot_set.count %}
                        {% for slot in titem.slot_set.all %}
                          {% if slot.state %}
                            {% with slot.shelf as shelf %}
                                {% with shelf.section.row as row %}
                                  <td>
                                      {{ row.rack.rack_group }}
                                      <br/>
                                      {% if row.rack.rack_group.blocker %}
                                        Заблокирован [{{ row.rack.rack_group.blocker }}]
                                      {% else %}
                                        Не блокирован
                                      {% endif %}
                                  </td>

                                  <td>
                                    {{ row }}
                                  </td>
                                {% endwith %}

                                <td>
                                  {{ shelf.section }}
                                </td>

                                <td>
                                  {{ shelf }}
                                </td>
                            {% endwith %}

                            <td>
                              {{ slot }}
                            </td>
                          {% endif %}
                        {% endfor %}
                    {% else %}
                        <td>
                          ...
                        </td>
                        <td>
                          ...
                        </td>
                        <td>
                          ...
                        </td>
                        <td>
                          ...
                        </td>
                        <td>
                          без места
                        </td>
                    {% endif %}
                {% endwith %}
              {% else %}
                  <td>
                    ---
                  </td>
                  <td>
                    ---
                  </td>
                  <td>
                    ---
                  </td>
                  <td>
                    ---
                  </td>
                  <td>
                    ---
                  </td>
              {% endif %}
              <!--
              endif task.item as titem
              -->
                  <td>
                    {{ task.owner }}
                  </td>

                  <td>
                  </td>
                </tr>
            {% endfor %}
        {% endfor %}
    </table>
{% endblock %}

archive/reports/templates/outtasks_pdf.html
{% extends "reports/base.html" %}
{% load helper_tags i18n static %}

{% block content %}
<h1 class="title">Операции Выдачи</h1>
<br/>
<br/>

<p>Дата создания отчета: <strong>{{ report_date }}.</strong> Имя пользователя: <strong>{{ report_user }}</strong></p>
<br/>
<br/>

<table cellspacing="2" class="stdAppTable" width="100%" border="1px">
        <tr>
            <th>Регистрационный №</th>
            <th>Наименование</th>
            <th>Комментарий</th>
            <th>Мобильная группа</th>
            <th>Ряд</th>
            <th>Секция</th>
            <th>Полка</th>
            <th>Место</th>
            <th>Пользователь</th>
            <th>Статус</th>
            <th></th>
        </tr>
        {% for mission in object_list %}
            {% for task in mission.task_set.all %}
            <tr>
              {% if task.item %}
                {% with task.item as titem %}
                    <td>{{ titem.number }}</td>
                    <td>{{ titem.name|default_if_none:'' }}</td>
                    <td>{{ task.description|default_if_none:'' }}</td>

                    {% if titem.slot_set.count %}
                        {% for slot in titem.slot_set.all %}
                          {% if slot.state %}
                            {% with slot.shelf as shelf %}
                                {% with shelf.section.row as row %}
                                  <td>
                                      {{ row.rack.rack_group }}
                                      <br/>
                                      {% if row.rack.rack_group.blocker %}
                                        Заблокирован [{{ row.rack.rack_group.blocker }}]
                                      {% else %}
                                        Не блокирован
                                      {% endif %}
                                  </td>

                                  <td>
                                    {{ row }}
                                  </td>
                                {% endwith %}

                                <td>
                                  {{ shelf.section }}
                                </td>

                                <td>
                                  {{ shelf }}
                                </td>
                            {% endwith %}

                            <td>
                              {{ slot }}
                            </td>
                          {% endif %}
                        {% endfor %}
                    {% else %}
                        <td>
                          ...
                        </td>
                        <td>
                          ...
                        </td>
                        <td>
                          ...
                        </td>
                        <td>
                          ...
                        </td>
                        <td>
                          без места
                        </td>
                    {% endif %}
                {% endwith %}
              {% else %}
                  <td>
                    ---
                  </td>
                  <td>
                    ---
                  </td>
                  <td>
                    ---
                  </td>
                  <td>
                    ---
                  </td>
                  <td>
                    ---
                  </td>
              {% endif %}
              <!--
              endif task.item as titem
              -->
                  <td>
                    {{ task.owner }}
                  </td>

                  <td>
                  </td>
                </tr>
            {% endfor %}
        {% endfor %}
    </table>
{% endblock %}

archive/reports/templates/removable_items_report_pdf.html
{% extends "reports/base.html" %}
{% load helper_tags i18n static %}

{% block content %}
<h3 class="title">Отчет по уничтожаемым единицам</h3>
<br/>
<br/>

<p>Уничтожение на дату: <strong>{{ report_input_date }}</strong>. Дата создания отчета: <strong>{{ report_date }}.</strong> Имя пользователя: <strong>{{ report_user }}</strong></p>
<br/>
<br/>

<table cellspacing="2" class="stdAppTable" width="100%" border="1px">
        {% if fields|length %}
            <tr>
                {% if 'number' in fields %}
                    <th>№ единицы<br/>хранения&nbsp;<br/></th>
                {% endif %}
                {% if 'name' in fields %}
                    <th>Наменование&nbsp;<br/></th>
                {% endif %}
                {% if 'created_by' in fields %}
                    <th>Создал&nbsp;<br/></th>
                {% endif %}
                {% if 'owner' in fields %}
                    <th>Ответственное<br/>лицо&nbsp;<br/></th>
                {% endif %}
                {% if 'rack_group' in fields %}
                    <th>Мобильная<br/>группа&nbsp;<br/></th>
                {% endif %}
                {% if 'department' in fields %}
                    <th>Отдел&nbsp;<br/></th>
                {% endif %}
                {% if 'item_type' in fields %}
                    <th>Тип единицы<br/>хранения&nbsp;<br/></th>
                {% endif %}
                {% if 'retention_policy' in fields %}
                    <th>Период<br/>хранения&nbsp;<br/></th>
                {% endif %}
                {% if 'created' in fields %}
                    <th>Дата<br/>создания&nbsp;<br/></th>
                {% endif %}
                {% if 'retention_date' in fields %}
                    <th>Дата<br/>уничтожения&nbsp;<br/></th>
                {% endif %}
            </tr>
        {% endif %}

    {% if fields|length %}
        {% for item in object_list %}
        <tr class="{% cycle 'odd' 'even' %}" class="bb">
            {% if 'number' in fields %}
            <td>
                {{ item.number }}
            </td>
            {% endif %}
            {% if 'name' in fields %}
            <td>
                {{ item.name|default_if_none:'-' }}
            </td>
            {% endif %}
            {% if 'created_by' in fields %}
            <td>
                {{ item.created_name }}
            </td>
            {% endif %}
            {% if 'owner' in fields %}
            <td>
                {{ item.owner }}
            </td>
            {% endif %}
            {% if 'rack_group' in fields %}
            <td>
                {% for slot in item.slot_set.all %}
                {% if slot.state == 3 or slot.state == 1 %}
                {% with slot.shelf as shelf %}
                {% with shelf.section.row as row %}
                {{ row.rack.rack_group }}
                <!--
                     <br/><br/>
                     {{ row|default_if_none:'-' }}
                     <br/><br/>
                   -->
                {% endwith %}
                <!--
                     {{ shelf.section }}
                     <br/>---<br/>
                     {{ shelf }}
                     <br/>---<br/>
                   -->
                {% endwith %}
                <br/>
                {{ slot }}
                <!--
                   -->
                {% endif %}
                {% endfor %}
            </td>
            {% endif %}
            {% if 'department' in fields %}
            <td>
                {{ item.department|default_if_none:'-' }}
            </td>
            {% endif %}
            {% if 'item_type' in fields %}
            <td>
                {{ item.item_type|default_if_none:'-' }}
            </td>
            {% endif %}
            {% if 'retention_policy' in fields %}
            <td>
                {{ item.retention_policy|default_if_none:'-' }}
            </td>
            {% endif %}
            {% if 'created' in fields %}
            <td>
                {{ item.created }}
            </td>
            {% endif %}
            {% if 'retention_date' in fields %}
            <td>
                {{ item.combined_date }}
            </td>
            {% endif %}
        </tr>
        {% endfor %}
    {% endif %}
</table>

{% endblock %}